version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production_backend
    ports:
      - '5005:5005'
    depends_on:
      - postgres
      - minio
      - redis
      - mongodb
    restart: unless-stopped
    command: >
      sh -c "
      npm run prisma:generate:prod &&
      npm start
      "

  postgres:
    image: postgres:latest
    container_name: production_database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'jit=off']
    # ports:
    #   - '5432:5432'
    ports:
      - '5432:5432'
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: production_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    # ports:
    #   - '9000:9000'
    expose: 
      - '9000'
    volumes:
      - minio_data:/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: production_redis
    # ports:
    #   - '6379:6379'
    expose:
      - '6379'
    restart: unless-stopped
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  mongodb:
    image: mongo:latest
    container_name: production_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    # ports:
    #   - '27017:27017'
    expose: 
      - '27017'

volumes:
  pg_data:
  minio_data:
